#!/bin/bash
set -x
export JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-x64
FDP_GUARDRAILS=/usr/share/fk-bigfoot-mr/share/hadoop/fdp-guardrails/lib/*:/usr/share/fk-bigfoot-mr/share/hadoop/fdp-guardrails/*:
export HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:${FDP_GUARDRAILS}
exec /usr/share/fk-bigfoot-mr/bin/hadoop "$@"
